# Generated by Django 4.0.3 on 2022-03-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_Naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.CharField(max_length=50)),
                ('telephone', models.PositiveIntegerField()),
                ('niveau', models.CharField(max_length=30)),
                ('filiere', models.CharField(max_length=50)),
                ('annee_Obtention_bac', models.DateField()),
                ('moyenne_Bac', models.CharField(max_length=10)),
                ('nature_Bac', models.CharField(max_length=50)),
            ],
        ),
    ]
