# Generated by Django 4.0.3 on 2022-03-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiants',
            name='moyenne_Bac',
            field=models.FloatField(max_length=10),
        ),
    ]
