# Generated by Django 4.0.3 on 2022-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0006_alter_etudiants_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiants',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
