# Generated by Django 4.0.3 on 2022-03-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0007_alter_etudiants_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'reconnaissande_de_visage_niveau',
            },
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='annee_Obtention_bac',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='moyenne_Bac',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='nature_Bac',
        ),
        migrations.AddField(
            model_name='etudiants',
            name='nni',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='telephone',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
