# Generated by Django 4.0.3 on 2022-03-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0008_niveau_remove_etudiants_annee_obtention_bac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('idNiveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reconnaissande_de_visage.niveau')),
            ],
            options={
                'db_table': 'reconnaissande_de_visage_filiere',
            },
        ),
    ]
