# Generated by Django 4.0.3 on 2022-03-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0009_filiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filiere',
            old_name='idNiveau',
            new_name='niveau',
        ),
    ]
