# Generated by Django 4.0.3 on 2022-03-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0010_rename_idniveau_filiere_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiants',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reconnaissande_de_visage.filiere'),
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reconnaissande_de_visage.niveau'),
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='nni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterModelTable(
            name='etudiants',
            table='reconnaissande_de_visage_etudiants',
        ),
    ]
