# Generated by Django 4.0.3 on 2022-03-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0011_alter_etudiants_filiere_alter_etudiants_niveau_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='etudiants',
            table=None,
        ),
    ]
