# Generated by Django 4.0.3 on 2022-03-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0012_alter_etudiants_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiants',
            old_name='filiere',
            new_name='filiere_id',
        ),
        migrations.RenameField(
            model_name='etudiants',
            old_name='niveau',
            new_name='niveau_id',
        ),
    ]
