# Generated by Django 4.0.3 on 2022-03-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0013_rename_filiere_etudiants_filiere_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='etudiants',
            table='reconnaissande_de_visage_etudiants',
        ),
    ]
