# Generated by Django 4.0.3 on 2022-03-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0015_rename_filiere_id_etudiants_filiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiants',
            name='nni',
            field=models.BigIntegerField(unique=True),
        ),
    ]
