# Generated by Django 4.0.3 on 2022-04-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconnaissande_de_visage', '0016_alter_etudiants_nni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiants',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='niveau',
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='nni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='telephone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterModelTable(
            name='etudiants',
            table=None,
        ),
    ]
